import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ThemeProvider } from "@/components/providers/theme-provider"
import { cn } from '@/lib/utils'
import ModalProvider from '@/components/providers/ModalProvider'
import NextAuthProvider from '@/components/providers/NextAuthProvider'
import { Toaster } from "@/components/ui/toaster"

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const session = await getServerSession(authOptions);
  console.log('in RootLayout')

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={cn( font.className, "bg-white dark:bg-[#313338]")}>
        <NextAuthProvider>
          <ThemeProvider 
            attribute="class" 
            defaultTheme="dark" 
            enableSystem={false}
            storageKey='discord-theme'
          >
            <ModalProvider/>
            <Toaster/>
            {children}
          </ThemeProvider>
          </NextAuthProvider>
        </body>
    </html>
  )
}
